- name: Allow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin yes"
              state=present

- name: Change root password
  user: name=root 
        password={{ ROOT_PASSWORD | password_hash('sha512') }} 
        shell=/bin/bash 
        update_password=always

- name: Reload ssh
  command: service ssh restart
