---
- hosts: all
  remote_user: www
  become: yes
  become_method: sudo

  vars:
    DEPLOY_USER_NAME: www
    SSH_KEYS:
    - ~/.ssh/id_rsa.pub

  roles:
  - name: "Install Nginx"
    role: nginx
    tags: [role_nginx]

  - name: "Install PostgreSQL"
    role: postgresql
    tags: [role_postgresql]

  - name: "Install Redis"
    role: redis
    tags: [role_redis]